server:
  port: 8080

spring:
  application:
    name: sistema-lima-accountingworker

cloud:
  aws:
    queue:
      processor: "processor_queue"

    topic:
      accounting:
        arn:

    region:
      static: "us-east-1"

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    beans.cache.time-to-live: 10s
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  metrics:
    export:
      prometheus:
        enabled: true
  health.circuitbreakers.enabled: true